language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
script:
  - npm test
  - npm run build
  - npm run docs
  - >
    if [[ ! -z $(git status --porcelain) ]] ; then
      echo "Please rebuild docs with 'npm run docs' and commit documentation changes.";
      exit 1;
    fi
branches:
  only:
  - master
  - stable
after_success:
  - export CODECOV_TOKEN="a2cb72ad-d773-4f47-ab17-398b2670489d"
  - npm i codecov
  - codecov
